spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: task-tracker
  mongodb:
    uri: ${MONGODB_URL}
    database: ${MONGODB_DATABASE}
  webflux:
    apiversion:
      default: 1
      use:
        path-segment: 1